# Generated by Django 2.2 on 2019-04-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-created_at']},
        ),
    ]
