# Generated by Django 2.2 on 2019-04-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsdiary', '0002_article_event_issue_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='categories',
        ),
    ]
