# Generated by Django 2.2 on 2019-04-16 15:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import newsdiary.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsdiary', '0003_remove_issue_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsdiary.Event'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsdiary.Issue'),
        ),
        migrations.AddField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='newsdiary.Issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(newsdiary.models.Category('정치'), '정치'), (newsdiary.models.Category('사회'), '사회'), (newsdiary.models.Category('경제'), '경제')], max_length=5), default=list, size=None),
        ),
        migrations.AddField(
            model_name='issue',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='following_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memo',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='newsdiary.Issue'),
        ),
        migrations.AddField(
            model_name='memo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL),
        ),
    ]
