# Generated by Django 2.2 on 2019-04-16 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdiary', '0004_auto_20190417_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
