# Generated by Django 2.2 on 2019-04-16 17:14

import django.contrib.postgres.fields
from django.db import migrations, models
import newsdiary.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdiary', '0007_auto_20190417_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
    ]
