# Generated by Django 2.2 on 2019-04-16 17:53

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdiary', '0008_auto_20190417_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
