# Generated by Django 2.2 on 2019-04-17 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsdiary', '0009_auto_20190417_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_newsdiary.noti_set+', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='article',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_article', to='newsdiary.Event'),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default='https://www.naver.com'),
        ),
        migrations.AddField(
            model_name='event',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='concept',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='importance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='newsdiary.Article'),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='NonregularNoti',
            fields=[
                ('noti_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newsdiary.Noti')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsdiary.Event')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsdiary.Issue')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('newsdiary.noti',),
        ),
    ]
