# Generated by Django 2.2 on 2019-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdiary', '0010_auto_20190417_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('POL', '정치'), ('SOC', '사회'), ('ECON', '경제')], max_length=20),
        ),
    ]
