# Generated by Django 2.2 on 2019-04-17 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsdiary', '0011_auto_20190417_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('POL', '정치'), ('SOC', '사회'), ('ECON', '경제')], max_length=20), default=list, size=None),
        ),
    ]
